import API from "../utils/apiBuilder";
import * as BoardController from "../controllers/BoardController";
import * as ListController from "../controllers/ListController";
import * as CardController from "../controllers/CardController";
import * as ActivityController from "../controllers/ActivityController";
import * as BoardMemberController from "../controllers/BoardMemberController";

const router = API.configRoute("/user")
  .addPath("/boards")
  .asGET(BoardController.list)
  .useUserAuth()
  .build()
  .addPath("/boards")
  .asPOST(BoardController.create)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId")
  .asGET(BoardController.getOne)
  .useUserAuth()
  .build()
  .addPath("/activity")
  .asGET(ActivityController.listForUser)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId/activity")
  .asGET(ActivityController.listByBoard)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId")
  .asDELETE(BoardController.remove)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId/invite")
  .asPOST(BoardMemberController.invite)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId/members")
  .asGET(BoardMemberController.listMembers)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId/members/:userId")
  .asDELETE(BoardMemberController.removeMember)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId/invitations/:invitationId")
  .asDELETE(BoardMemberController.cancelInvite)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId/lists")
  .asPOST(ListController.create)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId/lists/:listId")
  .asUPDATE(ListController.update)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId/lists/:listId")
  .asDELETE(ListController.remove)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId/lists/:listId/cards")
  .asPOST(CardController.create)
  .useUserAuth()
  .build()
  .addPath("/boards/:boardId/cards")
  .asGET(CardController.listByBoard)
  .useUserAuth()
  .build()
  .addPath("/cards/:cardId")
  .asUPDATE(CardController.update)
  .useUserAuth()
  .build()
  .addPath("/cards/:cardId")
  .asDELETE(CardController.remove)
  .useUserAuth()
  .build()
  .addPath("/cards/:cardId/move")
  .asUPDATE(CardController.move)
  .useUserAuth()
  .build()
  .getRouter();

export default router;
